version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - node_modules_volume:/workspace/node_modules:cached
      - ..:/workspace:cached
      - ~/.ssh:/home/node/.ssh_copy:cached
      - ~/.gitconfig:/home/node/.gitconfig
    ports:
      - 24678:24678 # HMR用のポートを追加
    tty: true

volumes:
  node_modules_volume:
