version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - node_modules_volume:/workspace/node_modules:cached
      - ..:/workspace:cached
      - ~/.ssh:/home/node/.ssh:cached
      - ~/.gitconfig:/home/node/.gitconfig:ro
    tty: true

volumes:
  node_modules_volume:
